# Generated by Django 2.0.4 on 2018-04-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(verbose_name='date sent')),
                ('msg', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=200)),
                ('recipient', models.CharField(max_length=200)),
            ],
        ),
    ]
