# Generated by Django 2.0.4 on 2018-04-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat_Msg',
            new_name='ChatMsg',
        ),
    ]
